name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 4 * *'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - 3.9
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
        toxenv:
          - py
        include:
          - python: '3.9'
            toxenv: typing
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install codecov coverage tox
    - name: Run tests
      run: tox -e ${{ matrix.toxenv }} && coverage xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        fail_ci_if_error: false
